/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.doan.view;

import com.doan.dao.billiardTableDAO;
import com.doan.model.billiard_table;
import java.util.ArrayList;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Asus
 */
public class BilliarTable extends javax.swing.JInternalFrame {

    /**
     * Creates new form BilliarTable
     */
    public BilliarTable() {
        initComponents();
        
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        if (ui.getNorthPane() != null) {
            ui.setNorthPane(null);        // Ẩn thanh tiêu đề
        }

        MainContent.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));
        

        ArrayList<billiard_table> listTAble = new billiardTableDAO().getInstance().selectAll();
        ArrayList<BilliarTableForm> list = new ArrayList<>();
        
        for (billiard_table x : listTAble) {
            BilliarTableForm billiarTableForm = new BilliarTableForm();
            billiarTableForm.setTableName(x.getTab_id());
            billiarTableForm.setBackgroundColor(x.getStatus());
            billiarTableForm.setPreferredSize(new java.awt.Dimension(170, 170)); // Kích thước cố định
            MainContent.add(billiarTableForm);
        }

        // Cập nhật giao diện
        MainContent.setPreferredSize(new java.awt.Dimension(1100, 847));
        MainContent.revalidate();
        MainContent.repaint();

                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        MainContent = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);

        MainContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout MainContentLayout = new javax.swing.GroupLayout(MainContent);
        MainContent.setLayout(MainContentLayout);
        MainContentLayout.setHorizontalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        MainContentLayout.setVerticalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 847, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(MainContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainContent;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
