/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.doan.view;

import com.doan.control.addNew;
import com.doan.control.delete;
import com.doan.control.edit;
import com.doan.control.generate;
import com.doan.dao.CueDAO;
import com.doan.model.cue;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class CueForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form CueForm
     */
    DefaultTableModel model;
    public CueForm() {
        initComponents();
        
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        if (ui.getNorthPane() != null) {
            ui.setNorthPane(null);        // Ẩn thanh tiêu đề
        }
        
        model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        String columns[] = {"Mã Gậy", "Tên Gậy", "Giá Thuê", "Số Lượng"};
        model.setColumnIdentifiers(columns);
        listCue.setModel(model);

        loadDataTable(new CueDAO().getInstance().selectAll());

        check();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCue = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdCue = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNameCue = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPriceCue = new javax.swing.JTextField();
        addNewCueBtn = new javax.swing.JButton();
        CancelAddNewBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtQuantityCue = new javax.swing.JTextField();
        editInfoCue = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEditIdCue = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEditNameCue = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEditPriceCue = new javax.swing.JTextField();
        saveNewInfoBtn = new javax.swing.JButton();
        CancelSaveNewInfoBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtEditQuantityCue = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        addNewCue = new javax.swing.JButton();
        delteCue = new javax.swing.JButton();
        editCue = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCue = new javax.swing.JTable();

        addCue.setTitle("Thêm Gậy Mới");
        addCue.setModal(true);
        addCue.setResizable(false);
        addCue.setSize(new java.awt.Dimension(1000, 600));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(0, 64, 140));

        jLabel1.setBackground(new java.awt.Color(0, 64, 140));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm Gậy Bida Mới");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Mã Gậy");

        txtIdCue.setBackground(java.awt.SystemColor.controlHighlight);
        txtIdCue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtIdCue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtIdCue.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Tên Gậy");

        txtNameCue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Giá Gậy");

        txtPriceCue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        addNewCueBtn.setBackground(new java.awt.Color(51, 153, 0));
        addNewCueBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        addNewCueBtn.setForeground(new java.awt.Color(255, 255, 255));
        addNewCueBtn.setText("Thêm Gậy");
        addNewCueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewCueBtnActionPerformed(evt);
            }
        });

        CancelAddNewBtn.setBackground(new java.awt.Color(255, 51, 51));
        CancelAddNewBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CancelAddNewBtn.setForeground(new java.awt.Color(255, 255, 255));
        CancelAddNewBtn.setText("HỦY");
        CancelAddNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelAddNewBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Số Lượng");

        txtQuantityCue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(addNewCueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(CancelAddNewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)
                            .addComponent(txtQuantityCue, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(45, 45, 45)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtIdCue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNameCue)
                                .addComponent(txtPriceCue, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(261, 261, 261))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdCue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNameCue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPriceCue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantityCue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelAddNewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewCueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout addCueLayout = new javax.swing.GroupLayout(addCue.getContentPane());
        addCue.getContentPane().setLayout(addCueLayout);
        addCueLayout.setHorizontalGroup(
            addCueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addCueLayout.setVerticalGroup(
            addCueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        editInfoCue.setTitle("Chỉnh Sửa Thông Tin Gậy");
        editInfoCue.setModal(true);
        editInfoCue.setResizable(false);
        editInfoCue.setSize(new java.awt.Dimension(1000, 600));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(0, 64, 140));

        jLabel5.setBackground(new java.awt.Color(0, 64, 140));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Chỉnh Sửa Thông Tin Gậy");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Mã Gậy");

        txtEditIdCue.setBackground(new java.awt.Color(204, 204, 204));
        txtEditIdCue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtEditIdCue.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Tên Gậy");

        txtEditNameCue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Giá Gậy");

        txtEditPriceCue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        saveNewInfoBtn.setBackground(new java.awt.Color(51, 153, 0));
        saveNewInfoBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        saveNewInfoBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveNewInfoBtn.setText("LƯU");
        saveNewInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewInfoBtnActionPerformed(evt);
            }
        });

        CancelSaveNewInfoBtn.setBackground(new java.awt.Color(255, 51, 51));
        CancelSaveNewInfoBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CancelSaveNewInfoBtn.setForeground(new java.awt.Color(255, 255, 255));
        CancelSaveNewInfoBtn.setText("HỦY");
        CancelSaveNewInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelSaveNewInfoBtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Số Lượng");

        txtEditQuantityCue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(saveNewInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(CancelSaveNewInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEditIdCue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEditNameCue)
                            .addComponent(txtEditPriceCue, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtEditQuantityCue))))
                .addGap(264, 264, 264))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEditIdCue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEditNameCue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditPriceCue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEditQuantityCue)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelSaveNewInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveNewInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout editInfoCueLayout = new javax.swing.GroupLayout(editInfoCue.getContentPane());
        editInfoCue.getContentPane().setLayout(editInfoCueLayout);
        editInfoCueLayout.setHorizontalGroup(
            editInfoCueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        editInfoCueLayout.setVerticalGroup(
            editInfoCueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chỉnh Sửa"));
        jToolBar1.setRollover(true);

        addNewCue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/add.png"))); // NOI18N
        addNewCue.setText("Thêm");
        addNewCue.setFocusable(false);
        addNewCue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addNewCue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addNewCue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewCueActionPerformed(evt);
            }
        });
        jToolBar1.add(addNewCue);

        delteCue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/delete.png"))); // NOI18N
        delteCue.setText("Xóa");
        delteCue.setFocusable(false);
        delteCue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        delteCue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        delteCue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delteCueActionPerformed(evt);
            }
        });
        jToolBar1.add(delteCue);

        editCue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/edit.png"))); // NOI18N
        editCue.setText("Chỉnh Sửa");
        editCue.setFocusable(false);
        editCue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editCue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editCue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCueActionPerformed(evt);
            }
        });
        jToolBar1.add(editCue);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(904, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(null);

        listCue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listCue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listCue.setRowHeight(30);
        listCue.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listCue);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewCueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewCueBtnActionPerformed
        // TODO add your handling code here:
        if (txtNameCue.getText().isEmpty() || txtPriceCue.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int x = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn thêm cue mới không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (x != JOptionPane.YES_OPTION) {
            return;
        }
        String id = txtIdCue.getText();
        String name = txtNameCue.getText();
        Double price = Double.parseDouble(txtPriceCue.getText());
        int quantity = Integer.parseInt(txtQuantityCue.getText());
        if (quantity < 0) {
            JOptionPane.showMessageDialog(null, "Số lượng không được âm!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        new addNew().getInstance().addNewCue(id, name, price, quantity);
        
        txtIdCue.setText("");
        txtNameCue.setText("");
        txtPriceCue.setText("");
        txtQuantityCue.setText("");

        JOptionPane.showMessageDialog(null, "Thêm gậy thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        addCue.setVisible(false);
        loadDataTable(new CueDAO().getInstance().selectAll());
    }//GEN-LAST:event_addNewCueBtnActionPerformed

    private void CancelAddNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelAddNewBtnActionPerformed
        // TODO add your handling code here:
        txtNameCue.setText("");
        txtPriceCue.setText("");
        txtQuantityCue.setText("");
        addCue.setVisible(false);
    }//GEN-LAST:event_CancelAddNewBtnActionPerformed

    private void saveNewInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewInfoBtnActionPerformed
        // TODO add your handling code here:
        if (txtEditNameCue.getText().isEmpty() || txtEditPriceCue.getText().isEmpty() || txtEditQuantityCue.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int x = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn lưu thay đổi không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (x != JOptionPane.YES_OPTION) {
            return;
        }
        String id = txtEditIdCue.getText();
        String name = txtEditNameCue.getText();
        Double price = Double.parseDouble(txtEditPriceCue.getText());
        int quantity = Integer.parseInt(txtEditQuantityCue.getText());

        new edit().getInstance().editCue(id, name, price, quantity);

        JOptionPane.showMessageDialog(null, "Lưu thông tin gậy thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        txtEditIdCue.setText("");
        txtEditNameCue.setText("");
        txtEditPriceCue.setText("");
        txtEditQuantityCue.setText("");
        editInfoCue.setVisible(false);
        loadDataTable(new CueDAO().getInstance().selectAll());
    }//GEN-LAST:event_saveNewInfoBtnActionPerformed

    private void CancelSaveNewInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelSaveNewInfoBtnActionPerformed
        // TODO add your handling code here:
        editInfoCue.setVisible(false);
    }//GEN-LAST:event_CancelSaveNewInfoBtnActionPerformed

    private void addNewCueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewCueActionPerformed
        // TODO add your handling code here:
        txtIdCue.setText(new generate().getInstance().generateIdCue());
        addCue.setLocationRelativeTo(null);
        addCue.setVisible(true);
    }//GEN-LAST:event_addNewCueActionPerformed

    private void delteCueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delteCueActionPerformed
        // TODO add your handling code here:
        int i_row = listCue.getSelectedRow();
        if (i_row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn gậy cần xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int x = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa gậy không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (x != JOptionPane.YES_OPTION) {
            return;
        }
        String id = listCue.getValueAt(i_row, 0).toString();
        new delete().getInstance().deleteCue(id);
        JOptionPane.showMessageDialog(null, "Xóa gậy thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        loadDataTable(new CueDAO().getInstance().selectAll());
    }//GEN-LAST:event_delteCueActionPerformed

    private void editCueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCueActionPerformed
        // TODO add your handling code here:
        int i_row = listCue.getSelectedRow();
        if (i_row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn gậy cần chỉnh sửa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
        txtEditIdCue.setText(listCue.getValueAt(i_row, 0).toString());
        txtEditNameCue.setText(listCue.getValueAt(i_row, 1).toString());
        txtEditPriceCue.setText(listCue.getValueAt(i_row, 2).toString());
        txtEditQuantityCue.setText(listCue.getValueAt(i_row, 3).toString());
        editInfoCue.setLocationRelativeTo(null);
        editInfoCue.setVisible(true);
    }//GEN-LAST:event_editCueActionPerformed

    public void loadDataTable(List<cue> list) {
        model.setRowCount(0);
        for (cue x : list) {
            if (x.isIs_delete() == false) {
                model.addRow(new Object[]{
                    x.getCue_id(),
                    x.getCue_name(),
                    x.getCue_price(),
                    x.getCue_quantity()
                });
            }
        }
    }

    public void check(){
        txtPriceCue.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
                    evt.consume();
                    javax.swing.JOptionPane.showMessageDialog(null, "Vui lòng chỉ nhập số!", "Lỗi nhập liệu", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        txtQuantityCue.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
                    evt.consume();
                    javax.swing.JOptionPane.showMessageDialog(null, "Vui lòng chỉ nhập số!", "Lỗi nhập liệu", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        txtEditPriceCue.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
                    evt.consume();
                    javax.swing.JOptionPane.showMessageDialog(null, "Vui lòng chỉ nhập số!", "Lỗi nhập liệu", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        txtEditQuantityCue.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
                    evt.consume();
                    javax.swing.JOptionPane.showMessageDialog(null, "Vui lòng chỉ nhập số!", "Lỗi nhập liệu", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelAddNewBtn;
    private javax.swing.JButton CancelSaveNewInfoBtn;
    private javax.swing.JDialog addCue;
    private javax.swing.JButton addNewCue;
    private javax.swing.JButton addNewCueBtn;
    private javax.swing.JButton delteCue;
    private javax.swing.JButton editCue;
    private javax.swing.JDialog editInfoCue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable listCue;
    private javax.swing.JButton saveNewInfoBtn;
    private javax.swing.JLabel txtEditIdCue;
    private javax.swing.JTextField txtEditNameCue;
    private javax.swing.JTextField txtEditPriceCue;
    private javax.swing.JTextField txtEditQuantityCue;
    private javax.swing.JLabel txtIdCue;
    private javax.swing.JTextField txtNameCue;
    private javax.swing.JTextField txtPriceCue;
    private javax.swing.JTextField txtQuantityCue;
    // End of variables declaration//GEN-END:variables
}
