/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.doan.view;

import com.doan.control.addNew;
import com.doan.control.delete;
import com.doan.control.edit;
import com.doan.control.generate;
import com.doan.dao.ItemDAO;
import com.doan.model.item;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class ItemForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ItemForm
     */
    DefaultTableModel model;
    public ItemForm() {
        initComponents();
        
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        if (ui.getNorthPane() != null) {
            ui.setNorthPane(null);        // Ẩn thanh tiêu đề
        }
        
        model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        String columns[] = {"Mã Sản Phẩm", "Tên Sản Phẩm", "Số lượng", "Giá"};
        model.setColumnIdentifiers(columns);
        listItem.setModel(model);
        
        setDataTable(new ItemDAO().getInstance().selectAll());
        
        check();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addNewItem = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        txtIdItem = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNameItem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPriceItem = new javax.swing.JTextField();
        addNewItemBtn = new javax.swing.JButton();
        CancelAddNewBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtQuantityItem = new javax.swing.JTextField();
        editItem = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        saveNewInfoBtn = new javax.swing.JButton();
        CancelSaveNewInfoBtn = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        txtEditId = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEdiName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEditPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEditQuantity = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        addNewBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        editInfoBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listItem = new javax.swing.JTable();

        addNewItem.setTitle("Thêm Sản Phẩm");
        addNewItem.setModal(true);
        addNewItem.setSize(new java.awt.Dimension(1000, 800));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(0, 64, 140));

        jLabel1.setBackground(new java.awt.Color(0, 64, 140));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm Sản Phẩm Mới");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label.setText("Mã Sản Phẩm");

        txtIdItem.setBackground(java.awt.SystemColor.controlHighlight);
        txtIdItem.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtIdItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtIdItem.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Tên Sản Phẩm");

        txtNameItem.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Giá Sản Phẩm");

        txtPriceItem.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        addNewItemBtn.setBackground(new java.awt.Color(51, 153, 0));
        addNewItemBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        addNewItemBtn.setForeground(new java.awt.Color(255, 255, 255));
        addNewItemBtn.setText("Thêm ");
        addNewItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewItemBtnActionPerformed(evt);
            }
        });

        CancelAddNewBtn.setBackground(new java.awt.Color(255, 51, 51));
        CancelAddNewBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CancelAddNewBtn.setForeground(new java.awt.Color(255, 255, 255));
        CancelAddNewBtn.setText("HỦY");
        CancelAddNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelAddNewBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Số Lượng");

        txtQuantityItem.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(addNewItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelAddNewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(45, 45, 45)
                        .addComponent(txtQuantityItem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(45, 45, 45))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNameItem)
                            .addComponent(txtPriceItem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(250, 250, 250))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNameItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPriceItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantityItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(addNewItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(CancelAddNewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );

        javax.swing.GroupLayout addNewItemLayout = new javax.swing.GroupLayout(addNewItem.getContentPane());
        addNewItem.getContentPane().setLayout(addNewItemLayout);
        addNewItemLayout.setHorizontalGroup(
            addNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addNewItemLayout.setVerticalGroup(
            addNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        editItem.setTitle("Chỉnh Sửa Thông Tin Sản Phẩm");
        editItem.setModal(true);
        editItem.setSize(new java.awt.Dimension(1000, 800));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(0, 64, 140));

        jLabel5.setBackground(new java.awt.Color(0, 64, 140));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Chỉnh Sửa Thông Tin Gậy");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        saveNewInfoBtn.setBackground(new java.awt.Color(51, 153, 0));
        saveNewInfoBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        saveNewInfoBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveNewInfoBtn.setText("LƯU");
        saveNewInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewInfoBtnActionPerformed(evt);
            }
        });

        CancelSaveNewInfoBtn.setBackground(new java.awt.Color(255, 51, 51));
        CancelSaveNewInfoBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CancelSaveNewInfoBtn.setForeground(new java.awt.Color(255, 255, 255));
        CancelSaveNewInfoBtn.setText("HỦY");
        CancelSaveNewInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelSaveNewInfoBtnActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label1.setText("Mã Sản Phẩm");

        txtEditId.setBackground(java.awt.SystemColor.controlHighlight);
        txtEditId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtEditId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtEditId.setOpaque(true);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Tên Sản Phẩm");

        txtEdiName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Giá Sản Phẩm");

        txtEditPrice.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Số Lượng");

        txtEditQuantity.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveNewInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157)
                .addComponent(CancelSaveNewInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(196, 196, 196)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(45, 45, 45)
                            .addComponent(txtEditQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(45, 45, 45))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEditId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEdiName)
                                .addComponent(txtEditPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(197, 197, 197)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 390, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelSaveNewInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveNewInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEditId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(44, 44, 44)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEdiName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(44, 44, 44)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEditPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(44, 44, 44)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEditQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(104, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout editItemLayout = new javax.swing.GroupLayout(editItem.getContentPane());
        editItem.getContentPane().setLayout(editItemLayout);
        editItemLayout.setHorizontalGroup(
            editItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        editItemLayout.setVerticalGroup(
            editItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chỉnh Sửa"));
        jToolBar1.setRollover(true);

        addNewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/add.png"))); // NOI18N
        addNewBtn.setText("Thêm");
        addNewBtn.setFocusable(false);
        addNewBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addNewBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(addNewBtn);

        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/delete.png"))); // NOI18N
        delBtn.setText("Xóa");
        delBtn.setFocusable(false);
        delBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        delBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(delBtn);

        editInfoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/edit.png"))); // NOI18N
        editInfoBtn.setText("Chỉnh Sửa");
        editInfoBtn.setFocusable(false);
        editInfoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editInfoBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editInfoBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(editInfoBtn);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        listItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listItem.setRowHeight(30);
        jScrollPane1.setViewportView(listItem);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(905, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBtnActionPerformed
        // TODO add your handling code here:
        txtIdItem.setText(new generate().getInstance().generateIdItem());
        addNewItem.setLocationRelativeTo(null);
        addNewItem.setVisible(true);
        
    }//GEN-LAST:event_addNewBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
        int i = listItem.getSelectedRow();
        if (i == -1){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn sản phẩm cần xóa");
            return;
        }
        int x = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa sản phẩm này không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (x != JOptionPane.YES_OPTION){
            return;
        }
        String id = (String) listItem.getValueAt(i, 0);
        new delete().getInstance().deleteItem(id);
        JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công");
        setDataTable(new ItemDAO().getInstance().selectAll());
    }//GEN-LAST:event_delBtnActionPerformed

    private void editInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInfoBtnActionPerformed
        // TODO add your handling code here:
        int i = listItem.getSelectedRow();
        if (i == -1){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn sản phẩm cần chỉnh sửa");
            return;
        }
        txtEditId.setText((String) listItem.getValueAt(i, 0));
        txtEdiName.setText((String) listItem.getValueAt(i, 1));
        txtEditQuantity.setText(String.valueOf(listItem.getValueAt(i, 2)));
        txtEditPrice.setText(String.valueOf(listItem.getValueAt(i, 3)));
        editItem.setLocationRelativeTo(null);
        editItem.setVisible(true);
    }//GEN-LAST:event_editInfoBtnActionPerformed

    private void addNewItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewItemBtnActionPerformed
        // TODO add your handling code here:
        if (txtNameItem.getText().isEmpty() || txtPriceItem.getText().isEmpty() || txtQuantityItem.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
            return;
        }
        int x = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn thêm sản phẩm này không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (x != JOptionPane.YES_OPTION){
            return;
        }
        String id = txtIdItem.getText();
        String name = txtNameItem.getText();
        int quantity = Integer.parseInt(txtQuantityItem.getText());
        double price = Double.parseDouble(txtPriceItem.getText());

        new addNew().getInstance().addNewItem(id, name, quantity, price);
        JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công");
        txtIdItem.setText("");
        txtNameItem.setText("");
        txtPriceItem.setText("");
        txtQuantityItem.setText("");
        setDataTable(new ItemDAO().getInstance().selectAll());
        addNewItem.setVisible(false);
    }//GEN-LAST:event_addNewItemBtnActionPerformed

    private void CancelAddNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelAddNewBtnActionPerformed
        // TODO add your handling code here:
        addNewItem.setVisible(false);
    }//GEN-LAST:event_CancelAddNewBtnActionPerformed

    private void saveNewInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewInfoBtnActionPerformed
        // TODO add your handling code here:
        if (txtEdiName.getText().isEmpty() || txtEditPrice.getText().isEmpty() || txtEditQuantity.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
            return;
        }
        int x = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn chỉnh sửa sản phẩm này không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (x != JOptionPane.YES_OPTION){
            return;
        }
        String id = txtEditId.getText();
        String name = txtEdiName.getText();
        int quantity = Integer.parseInt(txtEditQuantity.getText());
        double price = Double.parseDouble(txtEditPrice.getText()); 
        new edit().getInstance().editItem(id, name, quantity, price);
        JOptionPane.showMessageDialog(null, "Chỉnh sửa sản phẩm thành công");
        txtEditId.setText("");
        txtEdiName.setText("");
        txtEditPrice.setText("");
        txtEditQuantity.setText("");
        setDataTable(new ItemDAO().getInstance().selectAll());
        editItem.setVisible(false);
    }//GEN-LAST:event_saveNewInfoBtnActionPerformed

    private void CancelSaveNewInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelSaveNewInfoBtnActionPerformed
        // TODO add your handling code here:
        editItem.setVisible(false);
    }//GEN-LAST:event_CancelSaveNewInfoBtnActionPerformed

    private void setDataTable (List<item> list){
        model.setRowCount(0);
        for (item x : list){
            if (!x.isIs_delete()){
                model.addRow(new Object[]{
                    x.getItem_id(),
                    x.getItem_name(),
                    x.getItem_quantity(),
                    x.getItem_price()
                });
            }
        }
    }

    public void check(){
        txtPriceItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                    evt.consume();
                    JOptionPane.showMessageDialog(null, "Vui lòng chỉ nhập số!", "Lỗi nhập số", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        txtQuantityItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                    evt.consume();
                    JOptionPane.showMessageDialog(null, "Vui lòng chỉ nhập số!", "Lỗi nhập số", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        txtEditPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                    evt.consume();
                    JOptionPane.showMessageDialog(null, "Vui lòng chỉ nhập số!", "Lỗi nhập số", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        txtEditQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                    evt.consume();
                    JOptionPane.showMessageDialog(null, "Vui lòng chỉ nhập số!", "Lỗi nhập số", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelAddNewBtn;
    private javax.swing.JButton CancelSaveNewInfoBtn;
    private javax.swing.JButton addNewBtn;
    private javax.swing.JDialog addNewItem;
    private javax.swing.JButton addNewItemBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton editInfoBtn;
    private javax.swing.JDialog editItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JTable listItem;
    private javax.swing.JButton saveNewInfoBtn;
    private javax.swing.JTextField txtEdiName;
    private javax.swing.JLabel txtEditId;
    private javax.swing.JTextField txtEditPrice;
    private javax.swing.JTextField txtEditQuantity;
    private javax.swing.JLabel txtIdItem;
    private javax.swing.JTextField txtNameItem;
    private javax.swing.JTextField txtPriceItem;
    private javax.swing.JTextField txtQuantityItem;
    // End of variables declaration//GEN-END:variables
}
