/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.doan.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class managerForm extends javax.swing.JFrame {

    /**
     * Creates new form managerForm
     */
    public managerForm() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        BilliarTable bt = new BilliarTable();
        MainContent.removeAll();
        MainContent.add(bt).setVisible(true);
        bt.setSize(MainContent.getWidth(), MainContent.getHeight());
        MainContent.revalidate();
        MainContent.repaint();
        MainContent.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        nav = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        ItemBtn = new javax.swing.JButton();
        CueBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        tableBtn = new javax.swing.JButton();
        EmpBtn = new javax.swing.JButton();
        AccBtn = new javax.swing.JButton();
        ReportBtn = new javax.swing.JButton();
        MainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giao diện Quản Lý");
        setResizable(false);

        background.setBackground(new java.awt.Color(0, 64, 140));

        nav.setBackground(new java.awt.Color(0, 64, 140));

        homeBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/home48.png"))); // NOI18N
        homeBtn.setText("Trang Chủ");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        ItemBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ItemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/snack48.png"))); // NOI18N
        ItemBtn.setText("Dịch Vụ");
        ItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemBtnActionPerformed(evt);
            }
        });

        CueBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CueBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/cue48.png"))); // NOI18N
        CueBtn.setText("Gậy Bida");
        CueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CueBtnActionPerformed(evt);
            }
        });

        LogoutBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/logout48.png"))); // NOI18N
        LogoutBtn.setText("Đăng Xuất");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        tableBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tableBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/table48.png"))); // NOI18N
        tableBtn.setText("Bàn Bida");
        tableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableBtnActionPerformed(evt);
            }
        });

        EmpBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        EmpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/employees.png"))); // NOI18N
        EmpBtn.setText("Nhân Viên");

        AccBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        AccBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/account.png"))); // NOI18N
        AccBtn.setText("Tài Khoản");

        ReportBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ReportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/report.png"))); // NOI18N
        ReportBtn.setText("Thống Kê");

        javax.swing.GroupLayout navLayout = new javax.swing.GroupLayout(nav);
        nav.setLayout(navLayout);
        navLayout.setHorizontalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LogoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CueBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ItemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AccBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReportBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        navLayout.setVerticalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(tableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(CueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(EmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(AccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MainContentLayout = new javax.swing.GroupLayout(MainContent);
        MainContent.setLayout(MainContentLayout);
        MainContentLayout.setHorizontalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1164, Short.MAX_VALUE)
        );
        MainContentLayout.setVerticalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        BilliarTable bt = new BilliarTable();
        MainContent.removeAll();
        MainContent.add(bt).setVisible(true);
        bt.setSize(MainContent.getWidth(), MainContent.getHeight());
        MainContent.revalidate();
        MainContent.repaint();
        MainContent.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void tableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableBtnActionPerformed
        // TODO add your handling code here:
        TableForm tf = new TableForm();
        MainContent.removeAll();
        MainContent.add(tf).setVisible(true);
        tf.setSize(MainContent.getWidth(), MainContent.getHeight());
        MainContent.revalidate();
        MainContent.repaint();
        MainContent.setVisible(true);
    }//GEN-LAST:event_tableBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn đăng xuất không?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            this.dispose();
            loginForm lf = new loginForm();
            lf.setLocationRelativeTo(null); 
            lf.setVisible(true);
        }
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void CueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CueBtnActionPerformed
        // TODO add your handling code here:
        CueForm cf = new CueForm();
        MainContent.removeAll();
        MainContent.add(cf).setVisible(true);
        cf.setSize(MainContent.getWidth(), MainContent.getHeight());
        MainContent.revalidate();
        MainContent.repaint();
        MainContent.setVisible(true);
    }//GEN-LAST:event_CueBtnActionPerformed

    private void ItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemBtnActionPerformed
        // TODO add your handling code here:
        ProductForm pf = new ProductForm();
        MainContent.removeAll();
        MainContent.add(pf).setVisible(true);
        pf.setSize(MainContent.getWidth(), MainContent.getHeight());
        MainContent.revalidate();
        MainContent.repaint();
        MainContent.setVisible(true);
    }//GEN-LAST:event_ItemBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccBtn;
    private javax.swing.JButton CueBtn;
    private javax.swing.JButton EmpBtn;
    private javax.swing.JButton ItemBtn;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JPanel MainContent;
    private javax.swing.JButton ReportBtn;
    private javax.swing.JPanel background;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel nav;
    private javax.swing.JButton tableBtn;
    // End of variables declaration//GEN-END:variables
}
