/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.doan.view;

import com.doan.model.account;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class managerForm extends javax.swing.JFrame {

    /**
     * Creates new form managerForm
     */
    static account a = new account();
    public managerForm(account acc) {
        initComponents();
        a = acc;
        this.setLocationRelativeTo(null);
        BilliarTable bt = new BilliarTable(acc);
        MainContent.removeAll();
        MainContent.add(bt).setVisible(true);
        bt.setSize(MainContent.getWidth(), MainContent.getHeight());
        MainContent.revalidate();
        MainContent.repaint();
        MainContent.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        nav = new javax.swing.JPanel();
        LogoutBtn = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        homeBtn = new javax.swing.JButton();
        reservedBtn = new javax.swing.JButton();
        tableBtn = new javax.swing.JButton();
        CueBtn = new javax.swing.JButton();
        itemBtn = new javax.swing.JButton();
        serviceBtn = new javax.swing.JButton();
        cusBtn = new javax.swing.JButton();
        EmpBtn = new javax.swing.JButton();
        AccBtn = new javax.swing.JButton();
        ReportBtn = new javax.swing.JButton();
        MainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giao diện Quản Lý");
        setResizable(false);

        background.setBackground(new java.awt.Color(0, 64, 140));

        nav.setBackground(new java.awt.Color(0, 64, 140));

        LogoutBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/logout48.png"))); // NOI18N
        LogoutBtn.setText("Đăng Xuất");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        homeBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/home48.png"))); // NOI18N
        homeBtn.setText("Trang Chủ");
        homeBtn.setMargin(new java.awt.Insets(10, 14, 10, 14));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(homeBtn);

        reservedBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        reservedBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/reverve.png"))); // NOI18N
        reservedBtn.setText("Đặt Trước");
        reservedBtn.setMargin(new java.awt.Insets(10, 14, 10, 14));
        reservedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservedBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(reservedBtn);

        tableBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tableBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/table48.png"))); // NOI18N
        tableBtn.setText("Bàn Bida  ");
        tableBtn.setMargin(new java.awt.Insets(10, 14, 10, 14));
        tableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(tableBtn);

        CueBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CueBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/cue48.png"))); // NOI18N
        CueBtn.setText("Gậy Bida  ");
        CueBtn.setMargin(new java.awt.Insets(10, 14, 10, 14));
        CueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CueBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(CueBtn);

        itemBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        itemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/snack48.png"))); // NOI18N
        itemBtn.setText("Sản Phẩm");
        itemBtn.setMargin(new java.awt.Insets(10, 14, 10, 14));
        itemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(itemBtn);

        serviceBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        serviceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/food-and-drink-48.png"))); // NOI18N
        serviceBtn.setText("Dịch Vụ   ");
        serviceBtn.setMargin(new java.awt.Insets(10, 14, 10, 14));
        serviceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(serviceBtn);

        cusBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/customer48.png"))); // NOI18N
        cusBtn.setText("Khách Hàng");
        cusBtn.setMargin(new java.awt.Insets(10, 14, 10, 14));
        cusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(cusBtn);

        EmpBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        EmpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/employee48.png"))); // NOI18N
        EmpBtn.setText("Nhân Viên");
        EmpBtn.setMargin(new java.awt.Insets(10, 14, 10, 14));
        EmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(EmpBtn);

        AccBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        AccBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/account48.png"))); // NOI18N
        AccBtn.setText("Tài Khoản");
        AccBtn.setMargin(new java.awt.Insets(10, 14, 10, 14));
        AccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(AccBtn);

        ReportBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ReportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/analytics48.png"))); // NOI18N
        ReportBtn.setText("Thống Kê");
        ReportBtn.setMargin(new java.awt.Insets(10, 14, 10, 14));
        ReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(ReportBtn);

        javax.swing.GroupLayout navLayout = new javax.swing.GroupLayout(nav);
        nav.setLayout(navLayout);
        navLayout.setHorizontalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navLayout.setVerticalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MainContentLayout = new javax.swing.GroupLayout(MainContent);
        MainContent.setLayout(MainContentLayout);
        MainContentLayout.setHorizontalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1146, Short.MAX_VALUE)
        );
        MainContentLayout.setVerticalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        BilliarTable bt = new BilliarTable(a);
        MainContent.removeAll();
        MainContent.add(bt).setVisible(true);
        bt.setSize(MainContent.getWidth(), MainContent.getHeight());
        MainContent.revalidate();
        MainContent.repaint();
        MainContent.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void tableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableBtnActionPerformed
        // TODO add your handling code here:
        TableForm tf = new TableForm();
        MainContent.removeAll();
        MainContent.add(tf).setVisible(true);
        tf.setSize(MainContent.getWidth(), MainContent.getHeight());
        MainContent.revalidate();
        MainContent.repaint();
        MainContent.setVisible(true);
    }//GEN-LAST:event_tableBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn đăng xuất không?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            this.dispose();
            loginForm lf = new loginForm();
            lf.setLocationRelativeTo(null); 
            lf.setVisible(true);
        }
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void CueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CueBtnActionPerformed
        // TODO add your handling code here:
        CueForm cf = new CueForm();
        MainContent.removeAll();
        MainContent.add(cf).setVisible(true);
        cf.setSize(MainContent.getWidth(), MainContent.getHeight());
        MainContent.revalidate();
        MainContent.repaint();
        MainContent.setVisible(true);
    }//GEN-LAST:event_CueBtnActionPerformed

    private void serviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceBtnActionPerformed
        // TODO add your handling code here:
        ServiceForm pf = new ServiceForm();
        MainContent.removeAll();
        MainContent.add(pf).setVisible(true);
        pf.setSize(MainContent.getWidth(), MainContent.getHeight());
        MainContent.revalidate();
        MainContent.repaint();
        MainContent.setVisible(true);
    }//GEN-LAST:event_serviceBtnActionPerformed

    private void EmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpBtnActionPerformed
        // TODO add your handling code here:
        emInfo ei = new emInfo();
        MainContent.removeAll();
        MainContent.add(ei).setVisible(true);
        ei.setSize(MainContent.getWidth(), MainContent.getHeight());
        MainContent.revalidate();
        MainContent.repaint();
        MainContent.setVisible(true);
    }//GEN-LAST:event_EmpBtnActionPerformed

    private void AccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccBtnActionPerformed
        // TODO add your handling code here:
        accountForm af = new accountForm();
        MainContent.removeAll();
        MainContent.add(af).setVisible(true);
        af.setSize(MainContent.getWidth(), MainContent.getHeight());
        MainContent.revalidate();
        MainContent.repaint();
        MainContent.setVisible(true);
    }//GEN-LAST:event_AccBtnActionPerformed

    private void itemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBtnActionPerformed
        // TODO add your handling code here:
        ItemForm it = new ItemForm();
        MainContent.removeAll();
        MainContent.add(it).setVisible(true);
        it.setSize(MainContent.getWidth(), MainContent.getHeight());
        MainContent.revalidate();
        MainContent.repaint();
        MainContent.setVisible(true);
    }//GEN-LAST:event_itemBtnActionPerformed

    private void cusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusBtnActionPerformed
        // TODO add your handling code here:
        customerForm cf = new customerForm();
        MainContent.removeAll();
        MainContent.add(cf).setVisible(true);
        cf.setSize(MainContent.getWidth(), MainContent.getHeight());
        MainContent.revalidate();
        MainContent.repaint();
        MainContent.setVisible(true);
    }//GEN-LAST:event_cusBtnActionPerformed

    private void reservedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservedBtnActionPerformed
        // TODO add your handling code here:
        ReservedForm rf = new ReservedForm(a);
        MainContent.removeAll();
        MainContent.add(rf).setVisible(true);
        rf.setSize(MainContent.getWidth(), MainContent.getHeight());
        MainContent.revalidate();
        MainContent.repaint();
        MainContent.setVisible(true);
    }//GEN-LAST:event_reservedBtnActionPerformed

    private void ReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportBtnActionPerformed
        // TODO add your handling code here:
        ReportForm rf = new ReportForm();
        MainContent.removeAll();
        MainContent.add(rf).setVisible(true);
        rf.setSize(MainContent.getWidth(), MainContent.getHeight());
        MainContent.revalidate();
        MainContent.repaint();
        MainContent.setVisible(true);
    }//GEN-LAST:event_ReportBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managerForm(a).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccBtn;
    private javax.swing.JButton CueBtn;
    private javax.swing.JButton EmpBtn;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JPanel MainContent;
    private javax.swing.JButton ReportBtn;
    private javax.swing.JPanel background;
    private javax.swing.JButton cusBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton itemBtn;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel nav;
    private javax.swing.JButton reservedBtn;
    private javax.swing.JButton serviceBtn;
    private javax.swing.JButton tableBtn;
    // End of variables declaration//GEN-END:variables
}
