/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.doan.view;

import com.doan.dao.BillDAO;
import com.doan.dao.customerDAO;
import com.doan.dao.employeeDAO;
import com.doan.model.bill;
import com.doan.model.customer;
import com.doan.model.employee;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Asus
 */
public class ReportForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReportForm
     */
    DefaultTableModel model;
    public ReportForm() {
        initComponents();

        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        String [] header = {"Mã Hóa Đơn", "Ngày Lập", "Tổng Tiền", "Mã Bàn", "Nhân Viên", "Khách Hàng"};
        model.setColumnIdentifiers(header);
        listReport.setModel(model);

        MonthCombo.setSelectedIndex(LocalDate.now().getMonthValue() - 1);
        YearSpinner.setValue(LocalDate.now().getYear());

        loadData(new BillDAO().getBillInMonth(MonthCombo.getSelectedIndex() + 1, (int) YearSpinner.getValue()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        MonthCombo = new javax.swing.JComboBox<>();
        YearSpinner = new javax.swing.JSpinner();
        sreachReportBtn = new javax.swing.JButton();
        JScroll = new javax.swing.JScrollPane();
        listReport = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));
        jToolBar2.setRollover(true);

        MonthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12" }));
        jToolBar2.add(MonthCombo);

        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(YearSpinner, "#");
        NumberFormatter formatter = (NumberFormatter) editor.getTextField().getFormatter();
        formatter.setAllowsInvalid(false);
        formatter.setCommitsOnValidEdit(true);
        NumberFormat nf = (NumberFormat) formatter.getFormat();
        nf.setGroupingUsed(false);
        YearSpinner.setEditor(editor);
        jToolBar2.add(YearSpinner);

        sreachReportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/search.png"))); // NOI18N
        sreachReportBtn.setText("Tìm Kiếm");
        sreachReportBtn.setFocusable(false);
        sreachReportBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sreachReportBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sreachReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sreachReportBtnActionPerformed(evt);
            }
        });
        jToolBar2.add(sreachReportBtn);

        listReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JScroll.setViewportView(listReport);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Doanh Thu");

        total.setBackground(new java.awt.Color(255, 255, 255));
        total.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        total.setForeground(new java.awt.Color(204, 0, 0));
        total.setText("jLabel2");
        total.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JScroll)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 602, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(total))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sreachReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sreachReportBtnActionPerformed
        // TODO add your handling code here:
        loadData(new BillDAO().getBillInMonth(MonthCombo.getSelectedIndex() + 1, (int) YearSpinner.getValue())); 
    }//GEN-LAST:event_sreachReportBtnActionPerformed

    private void loadData (List<bill> list){
        model.setRowCount(0);
        if (list == null || list.isEmpty()) {
            total.setText("0 VNĐ");
            JOptionPane.showMessageDialog(this, "Không có dữ liệu trong tháng này", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        double totalAmount = 0;
        for (bill b : list){
            employee e = new employeeDAO().getInstance().selectById(b.getEmp_id());
            customer c = new customerDAO().getInstance().selectById(b.getCus_id());
            
            model.addRow(new Object[]{
                b.getBill_id(),
                b.getCreated_at(),
                b.getTotal(),
                b.getTab_id(),
                e.getEmp_name(),
                c.getCus_name()
            });
            totalAmount += b.getTotal();
        }
        total.setText(totalAmount + " VNĐ");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScroll;
    private javax.swing.JComboBox<String> MonthCombo;
    private javax.swing.JSpinner YearSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTable listReport;
    private javax.swing.JButton sreachReportBtn;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
