/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.doan.view;

import com.doan.control.addNew;
import com.doan.control.delete;
import com.doan.control.edit;
import com.doan.control.generate;
import com.doan.dao.billiardTableDAO;
import com.doan.model.billiard_table;
import java.awt.Color;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class TableForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form TableForm
     */

    DefaultTableModel model;
    public TableForm() {
        initComponents();

        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        if (ui.getNorthPane() != null) {
            ui.setNorthPane(null);        // Ẩn thanh tiêu đề
        }
        
        model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        tableList.setModel(model);
        String [] columns = {"Mã Bàn", "Tên Bàn", "Giá Bàn", "Trạng Thái"};
        model.setColumnIdentifiers(columns);
        
        List<billiard_table> list = new billiardTableDAO().getInstance().selectAll();
        loadDataTable(list);

        txttype.addItem("Thường");
        txttype.addItem("VIP");
        
        check();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBilliardTable = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdBilliardTable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNameBilliardTable = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPriceBilliardTable = new javax.swing.JTextField();
        addNewBilliardTableBtn = new javax.swing.JButton();
        CancelAddNewBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TypeTableCombo = new javax.swing.JComboBox<>();
        editBilliardTable = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEditIdBilliardTable = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEditNameBilliardTable = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEditPriceBilliardTable = new javax.swing.JTextField();
        saveNewInfoBtn = new javax.swing.JButton();
        CancelSaveNewInfoBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txttype = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        addNewBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        editInfoBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableList = new javax.swing.JTable();

        addBilliardTable.setModal(true);
        addBilliardTable.setResizable(false);
        addBilliardTable.setSize(new java.awt.Dimension(1000, 600));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(0, 64, 140));

        jLabel1.setBackground(new java.awt.Color(0, 64, 140));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm Bàn Bida Mới");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Mã Bàn");

        txtIdBilliardTable.setBackground(java.awt.SystemColor.controlHighlight);
        txtIdBilliardTable.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtIdBilliardTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtIdBilliardTable.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Tên Bàn");

        txtNameBilliardTable.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Giá Bàn");

        txtPriceBilliardTable.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        addNewBilliardTableBtn.setBackground(new java.awt.Color(51, 153, 0));
        addNewBilliardTableBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        addNewBilliardTableBtn.setForeground(new java.awt.Color(255, 255, 255));
        addNewBilliardTableBtn.setText("Thêm Bàn");
        addNewBilliardTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewBilliardTableBtnActionPerformed(evt);
            }
        });

        CancelAddNewBtn.setBackground(new java.awt.Color(255, 51, 51));
        CancelAddNewBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CancelAddNewBtn.setForeground(new java.awt.Color(255, 255, 255));
        CancelAddNewBtn.setText("HỦY");
        CancelAddNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelAddNewBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Loại Bàn");

        TypeTableCombo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TypeTableCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thường", "VIP" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdBilliardTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNameBilliardTable)
                            .addComponent(txtPriceBilliardTable, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(TypeTableCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(addNewBilliardTableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(CancelAddNewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(261, 261, 261))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdBilliardTable, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNameBilliardTable, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPriceBilliardTable, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(TypeTableCombo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelAddNewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewBilliardTableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout addBilliardTableLayout = new javax.swing.GroupLayout(addBilliardTable.getContentPane());
        addBilliardTable.getContentPane().setLayout(addBilliardTableLayout);
        addBilliardTableLayout.setHorizontalGroup(
            addBilliardTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addBilliardTableLayout.setVerticalGroup(
            addBilliardTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        editBilliardTable.setModal(true);
        editBilliardTable.setResizable(false);
        editBilliardTable.setSize(new java.awt.Dimension(1000, 600));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(0, 64, 140));

        jLabel5.setBackground(new java.awt.Color(0, 64, 140));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Chỉnh Sửa Thông Tin Bàn Bida");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Mã Bàn");

        txtEditIdBilliardTable.setBackground(new java.awt.Color(204, 204, 204));
        txtEditIdBilliardTable.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtEditIdBilliardTable.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Tên Bàn");

        txtEditNameBilliardTable.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Giá Bàn");

        txtEditPriceBilliardTable.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        saveNewInfoBtn.setBackground(new java.awt.Color(51, 153, 0));
        saveNewInfoBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        saveNewInfoBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveNewInfoBtn.setText("LƯU");
        saveNewInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewInfoBtnActionPerformed(evt);
            }
        });

        CancelSaveNewInfoBtn.setBackground(new java.awt.Color(255, 51, 51));
        CancelSaveNewInfoBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CancelSaveNewInfoBtn.setForeground(new java.awt.Color(255, 255, 255));
        CancelSaveNewInfoBtn.setText("HỦY");
        CancelSaveNewInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelSaveNewInfoBtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Loại Bàn");

        txttype.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(saveNewInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(CancelSaveNewInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEditIdBilliardTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEditNameBilliardTable)
                            .addComponent(txtEditPriceBilliardTable, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txttype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(264, 264, 264))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEditIdBilliardTable, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEditNameBilliardTable, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditPriceBilliardTable, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txttype)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelSaveNewInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveNewInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout editBilliardTableLayout = new javax.swing.GroupLayout(editBilliardTable.getContentPane());
        editBilliardTable.getContentPane().setLayout(editBilliardTableLayout);
        editBilliardTableLayout.setHorizontalGroup(
            editBilliardTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        editBilliardTableLayout.setVerticalGroup(
            editBilliardTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chỉnh Sửa"));
        jToolBar1.setRollover(true);

        addNewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/add.png"))); // NOI18N
        addNewBtn.setText("Thêm");
        addNewBtn.setFocusable(false);
        addNewBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addNewBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(addNewBtn);

        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/delete.png"))); // NOI18N
        delBtn.setText("Xóa");
        delBtn.setFocusable(false);
        delBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        delBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(delBtn);

        editInfoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doan/icon/edit.png"))); // NOI18N
        editInfoBtn.setText("Chỉnh Sửa");
        editInfoBtn.setFocusable(false);
        editInfoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editInfoBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editInfoBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(editInfoBtn);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tableList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableList.setRowHeight(30);
        tableList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableList);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewBilliardTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBilliardTableBtnActionPerformed
        // TODO add your handling code here:
        if (txtNameBilliardTable.getText().isEmpty() || txtPriceBilliardTable.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int x = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn thêm bàn bida mới không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (x != JOptionPane.YES_OPTION) {
            return;
        }
        String id = txtIdBilliardTable.getText();
        String name = txtNameBilliardTable.getText();
        Double price = Double.parseDouble(txtPriceBilliardTable.getText());
        String type = TypeTableCombo.getSelectedItem().toString();
        new addNew().getInstance().addNewBilliardTable(id, name, price, type);
        
        txtIdBilliardTable.setText("");
        txtNameBilliardTable.setText("");
        txtPriceBilliardTable.setText("");

        JOptionPane.showMessageDialog(null, "Thêm bàn thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

        addBilliardTable.setVisible(false);

        loadDataTable(new billiardTableDAO().getInstance().selectAll());
    }//GEN-LAST:event_addNewBilliardTableBtnActionPerformed

    private void saveNewInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewInfoBtnActionPerformed
        // TODO add your handling code here:
        if (txtEditNameBilliardTable.getText().isEmpty() || txtEditPriceBilliardTable.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int x = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn lưu thông tin bàn không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (x != JOptionPane.YES_OPTION) {
            return;
        }
        String id = txtEditIdBilliardTable.getText();
        String name = txtEditNameBilliardTable.getText();
        Double price = Double.parseDouble(txtEditPriceBilliardTable.getText());
        String type = txttype.getSelectedItem().toString();
        new edit().getInstance().editBilliardTable(id, name, price, type);

        JOptionPane.showMessageDialog(null, "Lưu thông tin bàn thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        editBilliardTable.setVisible(false);
        loadDataTable(new billiardTableDAO().getInstance().selectAll());
    }//GEN-LAST:event_saveNewInfoBtnActionPerformed

    private void addNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBtnActionPerformed
        // TODO add your handling code here:
        txtIdBilliardTable.setText(new generate().getInstance().generateIdTable());
        addBilliardTable.setLocationRelativeTo(null);
        addBilliardTable.setVisible(true);
    }//GEN-LAST:event_addNewBtnActionPerformed

    private void CancelAddNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelAddNewBtnActionPerformed
        // TODO add your handling code here:
        txtNameBilliardTable.setText("");
        txtPriceBilliardTable.setText("");
        addBilliardTable.setVisible(false);
    }//GEN-LAST:event_CancelAddNewBtnActionPerformed

    private void editInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInfoBtnActionPerformed
        // TODO add your handling code here:
        int i_row = tableList.getSelectedRow();
        if (i_row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn bàn cần chỉnh sửa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        txtEditIdBilliardTable.setText(tableList.getValueAt(i_row, 0).toString());
        txtEditNameBilliardTable.setText(tableList.getValueAt(i_row, 1).toString());
        txtEditPriceBilliardTable.setText(tableList.getValueAt(i_row, 2).toString());
        editBilliardTable.setLocationRelativeTo(null);
        editBilliardTable.setVisible(true);
    }//GEN-LAST:event_editInfoBtnActionPerformed

    private void CancelSaveNewInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelSaveNewInfoBtnActionPerformed
        // TODO add your handling code here:
        editBilliardTable.setVisible(false);
    }//GEN-LAST:event_CancelSaveNewInfoBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
        int i_row = tableList.getSelectedRow();
        if (i_row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn bàn cần xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int x = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa bàn không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (x != JOptionPane.YES_OPTION) {
            return;
        }
        String id = tableList.getValueAt(i_row, 0).toString();
        new delete().getInstance().deleteBilliardTable(id);
        JOptionPane.showMessageDialog(null, "Xóa bàn thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        loadDataTable(billiardTableDAO.getInstance().selectAll());
    }//GEN-LAST:event_delBtnActionPerformed

    public void loadDataTable(List<billiard_table> list) {
        model.setRowCount(0);
        for (billiard_table x : list) {
            if (x.isIs_delete() == false) {
                model.addRow(new Object[]{
                    x.getTab_id(),
                    x.getTab_name(),
                    x.getTab_price(),
                    x.getStatus()
                });
            }
        }
    }

    public void check(){
        txtPriceBilliardTable.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
                    evt.consume();
                    javax.swing.JOptionPane.showMessageDialog(null, "Vui lòng chỉ nhập số!", "Lỗi nhập liệu", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        txtEditPriceBilliardTable.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
                    evt.consume();
                    javax.swing.JOptionPane.showMessageDialog(null, "Vui lòng chỉ nhập số!", "Lỗi nhập liệu", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelAddNewBtn;
    private javax.swing.JButton CancelSaveNewInfoBtn;
    private javax.swing.JComboBox<String> TypeTableCombo;
    private javax.swing.JDialog addBilliardTable;
    private javax.swing.JButton addNewBilliardTableBtn;
    private javax.swing.JButton addNewBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JDialog editBilliardTable;
    private javax.swing.JButton editInfoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton saveNewInfoBtn;
    private javax.swing.JTable tableList;
    private javax.swing.JLabel txtEditIdBilliardTable;
    private javax.swing.JTextField txtEditNameBilliardTable;
    private javax.swing.JTextField txtEditPriceBilliardTable;
    private javax.swing.JLabel txtIdBilliardTable;
    private javax.swing.JTextField txtNameBilliardTable;
    private javax.swing.JTextField txtPriceBilliardTable;
    private javax.swing.JComboBox<String> txttype;
    // End of variables declaration//GEN-END:variables
}
